# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

services:

  orderer0.trade.com:
    container_name: orderer0.trade.com
    extends:
      file: orderer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/trade.com/orderers/orderer0.trade.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/trade.com/orderers/orderer0.trade.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 7050:7050

  orderer1.trade.com:
    container_name: orderer1.trade.com
    extends:
      file: orderer-base.yaml
      service: orderer-base
    volumes:
      - ../channel-artifacts/genesis.block:/var/hyperledger/orderer/orderer.genesis.block
      - ../crypto-config/ordererOrganizations/trade.com/orderers/orderer1.trade.com/msp:/var/hyperledger/orderer/msp
      - ../crypto-config/ordererOrganizations/trade.com/orderers/orderer1.trade.com/tls/:/var/hyperledger/orderer/tls
    ports:
      - 8050:8050

  peer0.exporterorg.trade.com:
    container_name: peer0.exporterorg.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.exporterorg.trade.com
      - CORE_PEER_ADDRESS=peer0.exporterorg.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.exporterorg.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.exporterorg.trade.com:7051
      - CORE_PEER_LOCALMSPID=ExporterOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/exporterorg.trade.com/peers/peer0.exporterorg.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/exporterorg.trade.com/peers/peer0.exporterorg.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer0.exporterorg.trade.com:/var/hyperledger/production
    ports:
      - 7051:7051
      - 7053:7053

  peer1.exporterorg.trade.com:
    container_name: peer1.exporterorg.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.exporterorg.trade.com
      - CORE_PEER_ADDRESS=peer1.exporterorg.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.exporterorg.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.exporterorg.trade.com:7051
      - CORE_PEER_LOCALMSPID=ExporterOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/exporterorg.trade.com/peers/peer1.exporterorg.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/exporterorg.trade.com/peers/peer1.exporterorg.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer1.exporterorg.trade.com:/var/hyperledger/production

    ports:
      - 7056:7051
      - 7058:7053

  peer0.importerorg.trade.com:
    container_name: peer0.importerorg.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.importerorg.trade.com
      - CORE_PEER_ADDRESS=peer0.importerorg.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.importerorg.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer1.importerorg.trade.com:7051
      - CORE_PEER_LOCALMSPID=ImporterOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/importerorg.trade.com/peers/peer0.importerorg.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/importerorg.trade.com/peers/peer0.importerorg.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer0.importerorg.trade.com:/var/hyperledger/production
    ports:
      - 8051:7051
      - 8053:7053

  peer1.importerorg.trade.com:
    container_name: peer1.importerorg.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer1.importerorg.trade.com
      - CORE_PEER_ADDRESS=peer1.importerorg.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.importerorg.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.importerorg.trade.com:7051
      - CORE_PEER_LOCALMSPID=ImporterOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/importerorg.trade.com/peers/peer1.importerorg.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/importerorg.trade.com/peers/peer1.importerorg.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer1.importerorg.trade.com:/var/hyperledger/production
    ports:
      - 8056:7051
      - 8058:7053

  peer0.exportingentityorg.trade.com:
    container_name: peer0.exportingentityorg.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.exportingentityorg.trade.com
      - CORE_PEER_ADDRESS=peer0.exportingentityorg.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.exportingentityorg.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.exportingentityorg.trade.com:7051
      - CORE_PEER_LOCALMSPID=ExportingEntityOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/exportingentityorg.trade.com/peers/peer0.exportingentityorg.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/exportingentityorg.trade.com/peers/peer0.exportingentityorg.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer0.exportingentityorg.trade.com:/var/hyperledger/production
    ports:
      - 9051:7051
      - 9053:7053

  peer0.carrierorg.trade.com:
    container_name: peer0.carrierorg.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.carrierorg.trade.com
      - CORE_PEER_ADDRESS=peer0.carrierorg.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.carrierorg.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.carrierorg.trade.com:7051
      - CORE_PEER_LOCALMSPID=CarrierOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/carrierorg.trade.com/peers/peer0.carrierorg.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/carrierorg.trade.com/peers/peer0.carrierorg.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer0.carrierorg.trade.com:/var/hyperledger/production
    ports:
      - 10051:7051
      - 10053:7053

  peer0.regulatororg.trade.com:
    container_name: peer0.regulatororg.trade.com
    extends:
      file: peer-base.yaml
      service: peer-base
    environment:
      - CORE_PEER_ID=peer0.regulatororg.trade.com
      - CORE_PEER_ADDRESS=peer0.regulatororg.trade.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.regulatororg.trade.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.regulatororg.trade.com:7051
      - CORE_PEER_LOCALMSPID=RegulatorOrgMSP
    volumes:
        - /var/run/:/host/var/run/
        - ../crypto-config/peerOrganizations/regulatororg.trade.com/peers/peer0.regulatororg.trade.com/msp:/etc/hyperledger/fabric/msp
        - ../crypto-config/peerOrganizations/regulatororg.trade.com/peers/peer0.regulatororg.trade.com/tls:/etc/hyperledger/fabric/tls
        - peer0.regulatororg.trade.com:/var/hyperledger/production
    ports:
      - 11051:7051
      - 11053:7053


  zookeeper0.trade.com:
    container_name: zookeeper0.trade.com
    extends:
      file: kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=1
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888

  zookeeper1.trade.com:
    container_name: zookeeper1.trade.com
    extends:
      file: kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=2
    ports:
      - 12181:2181
      - 12888:2888
      - 13888:3888

  zookeeper2.trade.com:
    container_name: zookeeper2.trade.com
    extends:
      file: kafka-base.yaml
      service: zookeeper
    environment:
      - ZOO_MY_ID=3
    ports:
      - 22181:2181
      - 22888:2888
      - 23888:3888

  kafka0.trade.com:
    container_name: kafka0.trade.com
    extends:
      file: kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=0
    ports:
      - 9092:9092
      - 9093:9093

  kafka1.trade.com:
    container_name: kafka1.trade.com
    extends:
      file: kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=1
    ports:
      - 10092:9092
      - 10093:9093

  kafka2.trade.com:
    container_name: kafka2.trade.com
    extends:
      file: kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=2
    ports:
      - 11092:9092
      - 11093:9093

  kafka3.trade.com:
    container_name: kafka3.trade.com
    extends:
      file: kafka-base.yaml
      service: kafka
    environment:
      - KAFKA_BROKER_ID=3
    ports:
      - 12092:9092
      - 12093:9093
      