# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#

version: '2'

volumes:
  ca.exporterorg.trade.com:
  ca.org2.trade.com:
  orderer0.trade.com:
  orderer1.trade.com:
  peer0.exporterorg.trade.com:
  peer1.exporterorg.trade.com:
  peer0.org2.trade.com:
  peer1.org2.trade.com:

networks:
  byfn:
    
services:
  ca.exporterorg.trade.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-exporterorg
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.exporterorg.trade.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.exporterorg.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA1_PRIVATE_KEY
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/exporterorg.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca-exporterorg

  ca.org2.trade.com:
    image: hyperledger/fabric-ca
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org2
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.trade.com-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org2.trade.com-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/CA2_PRIVATE_KEY
    ports:
      - "8054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw -d'
    volumes:
      - ./crypto-config/peerOrganizations/org2.trade.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca-org2

  orderer0.trade.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer0.trade.com
    container_name: orderer0.trade.com
    depends_on:
      - kafka0.trade.com
      - kafka1.trade.com
      - kafka2.trade.com
      - kafka3.trade.com  
    networks:
      - byfn
      
  orderer1.trade.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer1.trade.com
    container_name: orderer1.trade.com
    depends_on:
      - kafka0.trade.com
      - kafka1.trade.com
      - kafka2.trade.com
      - kafka3.trade.com  
    networks:
      - byfn      

  peer0.exporterorg.trade.com:
    container_name: peer0.exporterorg.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.exporterorg.trade.com
    networks:
      - byfn      

  peer1.exporterorg.trade.com:
    container_name: peer1.exporterorg.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.exporterorg.trade.com
    networks:
      - byfn      
      
  peer0.org2.trade.com:
    container_name: peer0.org2.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.org2.trade.com
    networks:
      - byfn      

  peer1.org2.trade.com:
    container_name: peer1.org2.trade.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer1.org2.trade.com
    networks:
      - byfn

  zookeeper0.trade.com:
    container_name: zookeeper0.trade.com
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper0.trade.com
    networks:
      - byfn      

  zookeeper1.trade.com:
    container_name: zookeeper1.trade.com
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper1.trade.com
    networks:
      - byfn      

  zookeeper2.trade.com:
    container_name: zookeeper2.trade.com
    extends:
      file: base/docker-compose-base.yaml
      service: zookeeper2.trade.com
    networks:
      - byfn      

  kafka0.trade.com:
    container_name: kafka0.trade.com
    extends:
      file: base/docker-compose-base.yaml
      service: kafka0.trade.com
    networks:
      - byfn         
    depends_on:
      - zookeeper0.trade.com
      - zookeeper1.trade.com
      - zookeeper2.trade.com

  kafka1.trade.com:
    container_name: kafka1.trade.com
    extends:
      file: base/docker-compose-base.yaml
      service: kafka1.trade.com
    networks:
      - byfn         
    depends_on:
      - zookeeper0.trade.com
      - zookeeper1.trade.com
      - zookeeper2.trade.com

  kafka2.trade.com:
    container_name: kafka2.trade.com
    extends:
      file: base/docker-compose-base.yaml
      service: kafka2.trade.com
    networks:
      - byfn         
    depends_on:
      - zookeeper0.trade.com
      - zookeeper1.trade.com
      - zookeeper2.trade.com

  kafka3.trade.com:
    container_name: kafka3.trade.com
    extends:
      file: base/docker-compose-base.yaml
      service: kafka3.trade.com
    networks:
      - byfn         
    depends_on:
      - zookeeper0.trade.com
      - zookeeper1.trade.com
      - zookeeper2.trade.com

  cli:
    container_name: cli
    image: hyperledger/fabric-tools:$IMAGE_TAG
    tty: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.exporterorg.trade.com:7051
      - CORE_PEER_LOCALMSPID=ExporterOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/exporterorg.trade.com/peers/peer0.exporterorg.trade.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/exporterorg.trade.com/peers/peer0.exporterorg.trade.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/exporterorg.trade.com/peers/peer0.exporterorg.trade.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/exporterorg.trade.com/users/Admin@exporterorg.trade.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    #command: /bin/bash -c 'sleep 1000'
    volumes:
        - /var/run/:/host/var/run/
        - ./examples/chaincode/:/opt/gopath/src/github.com/chaincode
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./scripts:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    networks:
      - byfn
    depends_on:
      - orderer0.trade.com
      - orderer1.trade.com
      - peer0.org2.trade.com
      - peer1.org2.trade.com
      - peer0.exporterorg.trade.com
      - peer1.exporterorg.trade.com
